name: Deploy to cPanel via SCP + SSH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project (creates out/)
        run: npm run build

      - name: Zip the out folder
        run: |
          cd out
          zip -r ../out.zip .
          cd ..
          ls -lh out.zip
          unzip -l out.zip

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Upload via SCP
        run: |
          sshpass -p "$SSHPASS" scp -o StrictHostKeyChecking=no -P 22 out.zip ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_SERVER }}:/home/suggesto/
        env:
          SSHPASS: ${{ secrets.CPANEL_PASSWORD }}

      - name: Extract via SSH
        run: |
          sshpass -p "$SSHPASS" ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.CPANEL_USERNAME }}@${{ secrets.CPANEL_SERVER }} << 'EOF'
            cd /home/suggesto
            unzip -o out.zip -d .
            rm out.zip
            ls -la
          EOF
        env:
          SSHPASS: ${{ secrets.CPANEL_PASSWORD }}

